### PR TITLE
Fix typo in Installation page Firmware Downloads text.

### PR DESCRIPTION
**Pull request by jpwhiting**
The link works, but the name should be 0419, not 0409.

### CODE REVIEW

**Comment by Aemiii91** [comment]
You can't edit docs this way. This repo is auto-generated from [Onion/website](https://github.com/OnionUI/Onion/tree/main/website). I've just put up a guide here: https://onionui.github.io/docs/dev/docs

**Comment by jpwhiting** [comment]
I see, thanks, doing the tweak there instead.

**Comment by Aemiii91** [comment]
Already done. Thanks!

**Comment by jpwhiting** [comment]
Yep, just saw right after I changed it locally in my fork. Thanks.

**Pull request closed without merging**
